"""empty message

Revision ID: 160573533604
Revises: 53e12ef5bdd4
Create Date: 2024-10-21 15:30:15.654292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160573533604'
down_revision = '53e12ef5bdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
